BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS products (
    id SERIAL,
    title VARCHAR(256) NOT NULL,
    img VARCHAR(256),
    price INTEGER NOT NULL,
    quantity INTEGER NOT NULL, ;
    author_id INTEGER,
    posted_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_products_author FOREIGN KEY (author_id) REFERENCES users(id)
) PARTITION BY HASH (price);

CREATE TABLE IF NOT EXISTS products_price_0_99 PARTITION OF products
    FOR VALUES WITH (MODULUS 3, REMAINDER 0);

CREATE TABLE IF NOT EXISTS products_price_100_199 PARTITION OF products
    FOR VALUES WITH (MODULUS 3, REMAINDER 1);

CREATE TABLE IF NOT EXISTS products_price_200_299 PARTITION OF products
    FOR VALUES WITH (MODULUS 3, REMAINDER 2);

COMMIT;